// try{
//     throw new Error('错误')

// }catch(e){
//     console.log(e)
// }